Host firewall
    HostName 10.29.0.1
    User root

Host oxygen
    HostName 10.29.0.10
    User root
    RemoteCommand tmux new-session -A -s main
    RequestTTY yes

Host web
    HostName 10.29.0.11
    User josh
    RemoteCommand tmux new-session -A -s main
    RequestTTY yes

Host media
    HostName 10.29.0.12
    User josh
    RemoteCommand cd /opt/app && exec $SHELL -l
    RequestTTY yes

Host game
    HostName 10.29.0.13
    User josh
    RemoteCommand tmux new-session -A -s main
    RequestTTY yes

Host lithium
    HostName 10.29.0.30
    User josh
    RemoteCommand tmux new-session -A -s main
    RequestTTY yes

Host sodium
    HostName 10.29.0.31
    User josh
    RemoteCommand tmux new-session -A -s main
    RequestTTY yes

Host ha
    HostName 10.29.0.15
    User root

Host jason-claude
    Hostname 100.124.156.8
    User jraymond

Host *
    IdentityFile ~/.ssh/id_ed25519
    IdentitiesOnly yes
    ServerAliveInterval 60
    ServerAliveCountMax 3
    ControlMaster auto
    ControlPath ~/.ssh/control/%r@%h:%p
    ControlPersist 10m
