Host freshgrow
    HostName fg.seradata.org
    ProxyCommand cloudflared access ssh --hostname %h
    Port 22
    User josh

Host freshgrow2
    HostName fg2.seradata.org
    ProxyCommand cloudflared access ssh --hostname %h
    Port 33556
    User josh

Host firewall
    HostName 10.29.0.1
    User root
    IdentityFile ~/.ssh/id_ed25519

Host oxygen
    HostName 10.29.0.10
    User root

Host web
    HostName 10.29.0.11
    User josh

Host media
    HostName 10.29.0.12
    User josh
    RemoteCommand cd /opt/app && exec $SHELL -l
    RequestTTY yes

Host game
    HostName 10.29.0.13
    User josh

Host lithium
    HostName 10.29.0.30
    User josh
    IdentityFile ~/.ssh/id_ed25519
    IdentitiesOnly yes

Host sodium
    HostName 10.29.0.31
    User josh
    IdentityFile ~/.ssh/id_ed25519
    IdentitiesOnly yes

Host helium
    HostName 192.168.1.190
    User josh

Host ha
    HostName 10.29.0.15
    User root
    IdentityFile ~/.ssh/id_ed25519

Host seraprod
    HostName 35.239.198.114
    User ext_josh_l8n_gmail_com
    IdentityFile ~/.ssh/id_ed25519

Host jason-claude
    Hostname 100.124.156.8
    User jraymond
